### ISSUE TITLE
content localisation 

### ISSUE THREAD

**Issue by violabg** [drupal-graphql/graphql-twig#12]
How would you localise content from query? 
I found that if I pass language as filter input to entities, the results are localised 

```graphql
works:nodeQuery(filter: {conditions: [{operator: EQUAL, field: "type", value: ["work"]}]}) {
      entities(language: IT) {
        ... on NodeWork {
          nid
          title
          services:fieldWorkServices {
            entity {
              nid
              title
            }
          }
          image:fieldWorkPreviewImage {
            url
          }
        }
      }
    }
```
But how do we pass the current language to the query?
Is there a better way for retrive localised content?
How do we pass calculated parameters to query, in general?

**Comment by pmelab** [comment]
The module tries to match template variables to query arguments. So if you have a variable `language` in the twig template, then you could use it as a query argument:

```graphql
works:nodeQuery(language: String!, filter: {conditions: [{operator: EQUAL, field: "type", value: ["work"]}]}) {
  entities(language: $language) {
    ...
  }
}
```
