### ISSUE TITLE
Compatible with Drupal 8.7.x ?

### ISSUE THREAD

**Issue by GiorgosK** [drupal-graphql/graphql-twig#14]
I was trying to test out this module following this webinar https://www.youtube.com/watch?v=QsmeXMZ0foM

I have setup graphql_twig and dependencies and graphiql using the explorer works as expected and returning the expected results

I have setup a simple bartik based graphql theme to follow the webinar above
and have created the exact same `block--bartik-graphql-powered.html.twig` template with the code mentioned in the webinar but also the drupal.org/project/graphql_twig page but nothing graphql is displayed

The **graphql-twig-debug-button** to **Inspect GraphQL query** is displayed and directs to the `/graphql/explorer` path and testing the query seems to produce the correct results. 

I have tried putting the twig template in 
`themes/custom/bartik_graphql/components/block--bartik-graphql-powered.html.twig`
`themes/custom/bartik_graphql/templates/components/block--bartik-graphql-powered.html.twig`
`themes/custom/bartik_graphql/templates/block--bartik-graphql-powered.html.twig`
and clearing cache before testing but it does not make any difference 

I am using lando for a local setup with drupal 8.7.4 which otherwise seems to work OK
could it be related to my setup ? or could it be related to 8.7 ? 
I have tried to investigate with a debugger but was hoping to narrow it down to where to look for before investing too much time on it.
Thanks for any help provided.

**Comment by evans863** [comment]
Following the same webinar I'm also not getting the GraphQL query to execute (or at least populate the resulting graphql object). The same query in the explorer works just fine.

Drupal: 8.7.8
PHP: 7.2.17

"drupal/graphql": "^3.0@RC"
"drupal/graphql_twig": "^1.0@beta"
"drupal/graphql_views": "^1.0@beta"
"drupal/graphql_xml": "^1.0@alpha"
"webonyx/graphql-php": "0.12.x-dev"

I've also had to change `{% extends '@bartik/block' %}` to `{% extends 'core/themes/bartik/templates/block.html.twig' %}` otherwise it says `@bartik/block` is undefined.

**Comment by evans863** [comment]
@GiorgosK So I was able to get this working and I'll explain what I've done to this point. I'm following the same webinar.

I have a D8 site setup using composer and the details of my site so far are as follows:

- Drupal: 8.7.8
- PHP: 7.2.17
- "drupal/graphql": "^3.0@RC"
- "drupal/graphql_twig": "^1.0@beta"
- "webonyx/graphql-php": "0.12.x-dev"

I had an issue with versioning with webonyx/graphql-php when trying to adding these three packages and 0.12.x-dev seemed to satisfy the issues graphql was having with webonyx/graphql-php.

My subtheme is as follows:

```
bartik_graphql
|
--- bartik_graphql.info.yml (same as the one they are using)
--- logo.svg (just copied the one from bartik theme)
--- templates/
   |
   --- block--bartik-graphql-powered.html.twig
```

If you haven't you'll want to enable and set your subtheme to the default theme.

`block--bartik-graphql-powered.htm.twig` is as follows:

```
{#graphql
  {
    admin:userById(id: "1") {
      name
    }
  }
}

{% extends 'core/themes/bartik/templates/block.html.twig' %}

{% block content %}
  <div{{ content_attributes.addClass('content') }}>
    {{ content }} and some guy named {{ graphql['admin']['name'] }}
  </div>
{% endblock %}
```

If you add `{{dump(graphql)}}` in your template file you'll notice it isn't anything like the webinar suggests. It spits out `array(1) { ["admin"]=> array(1) { ["name"]=> string(4) "NAME OF YOUR USER" } }`. No data object whatsoever, no dot notation. So if you use `{{ graphql['admin']['name'] }}` you might have more luck.

I couldn't get `{% extends '@bartik/block' %}` to work like they are able to around the 18 minute mark in the webinar.

Not sure why this is happening. Perhaps the webinar was using some legacy versions and this is how it is now. I haven't been able to find any info about it in my searches yet.

**Comment by pmelab** [comment]
We are moving issues and maintenance over to Drupal.org. I created an issue over there:
https://www.drupal.org/project/graphql_twig/issues/3091185
