### ISSUE TITLE
Dynamic query building

### ISSUE THREAD

**Issue by dermario** [drupal-graphql/graphql-twig#15]
Thank you for providing this awesome module. We really appreciate it a lot. Currently i am stuck with the following problem: I am using graphql search api module to set up some pages with filtered content and facets. One question that came up is, if there is a way to generate/alter graphql queries to have e.g. a dynamic amount of conditions.

Lets say i have the following query:

```javascript
  searchAPISearch(
    index_id: "keyword_index", 
    language: "de", 
    range: {start: 1, end: 50},
    conditions: [
      {operator: "=", name: "aggregated_terms", value: "34"}
    ] 
  )
  {
     // ...
  }
```

What i need is to have a dynamic `conditions` block, based on the amount of fields i want to filter for. So if i want to get results that match the ids 34, 35 and 36 i need to query this way:

```javascript
    // ...
    conditions: [
      {operator: "=", name: "aggregated_terms", value: "34"}
      {operator: "=", name: "aggregated_terms", value: "35"}
      {operator: "=", name: "aggregated_terms", value: "36"}
    ] 
    // ...
```
Is there a way/workaround to achieve that? Thanks a lot for pointing me in the right direction.

**Comment by pmelab** [comment]
The module tries to match template variables to query arguments. You could try to provide your assembled array of conditions to the template and then use it like this:
```
query ($conditions: [ConditionInput]) {
  searchAPISearch(
    index_id: "keyword_index", 
    language: "de", 
    range: {start: 1, end: 50},
    conditions: $conditions
  )
  {
     // ...
  }
}
```

In this case there has to be a variable in the twig template called `conditions`.
