### ISSUE TITLE
Provide an option to not wrap the debug on the element itself

### ISSUE THREAD

**Issue by saschaeggi** [drupal-graphql/graphql-twig#18]
Currently the debug output can break stuff in some scenarios where we need to rely on the use of CSS features like `:nth-of-type`.
The solution would be to provide a module option to have the debug output inside of the element itself – like Drupals own Contextual links.

**Comment by megadesk3000** [comment]
I created a patch for this, to make this configurable under /admin/config/services/graphql_twig
[graphql_twig_debug-18.txt](https://github.com/drupal-graphql/graphql-twig/files/3675053/graphql_twig_debug-18.txt)

**Comment by dan2k3k4** [comment]
@megadesk3000 you can fork this repository and then create a Pull-Request with the applied patch.

Set the title to include `Fixes #18` so that it auto-closes this issue once merged.

**Comment by megadesk3000** [comment]
@dan2k3k4 Ok, done :) https://github.com/drupal-graphql/graphql-twig/pull/19

**Comment by dan2k3k4** [comment]
#19 was merged so this can be closed @pmelab
