### ISSUE TITLE
[ERROR] You have requested a non-existent service "http_kernel.controller.argument_resolver".

### ISSUE THREAD

**Issue by AndyRead** [drupal-graphql/graphql-twig#4]
Error during module install.  I'm just exploring the module, so not yet clear what effect this has on its funcationality.

Drupal 8.5.6
GraphQL Twig 8.x-1.0-beta11

This is the only ref I can find to http_kernel.controller.argument_resolver:
graphql_twig/src/GraphqlTwigServiceProvider.php:25:    $def = $container->getDefinition('http_kernel.controller.argument_resolver');

I'm guessing it may be related to the Symfony 3.1 change discussed in this core issue https://www.drupal.org/project/drupal/issues/2912169

**Comment by hugovk** [comment]
I ran into this too, and I see from one of the commits in PR https://github.com/drupal-graphql/graphql-twig/pull/3 that GraphQL Twig is now Drupal-8.6 only, 8.4 and 8.5 have been dropped.

It would be great to make this clear in at least some of:

* https://github.com/drupal-graphql/graphql-twig/blob/8.x-1.x/README.md
* https://github.com/drupal-graphql/graphql-twig/blob/8.x-1.x/composer.json
* https://www.drupal.org/project/graphql_twig
* https://www.drupal.org/project/graphql_twig/releases/8.x-1.0-beta11

**Comment by pmelab** [comment]
If somebody needs support for 8.4/8.5: There is a small patch that could be applied.
https://github.com/drupal-graphql/graphql-twig/pull/6/files

The auto-routing feature won't work then any more though.
